services:
  snapsync:
    container_name: snapsync
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /:/hostfs
      - $SNAPSYNC_CONFIG_PATH:/snapsync/config.yml
      - $SNAPSYNC_SNAPSHOTS_CONFIGS_DIR:/snapsync/snapshots_configs