services:
  snapsync:
    container_name: snapsync
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /:/hostfs
      - $SNAPSYNC_CONFIGS_DIR:/snapsync/snapshots_configs